spring.application.name=integration
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.datetime-format=yyyy-MM-dd'T'HH:mm:ss'Z'

jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.access-token-expiration=180000
jwt.refresh-token-expiration=300000

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT_URI}

logging.level.com.mxr.integration=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
